//go:build integration

package main

import (
	"context"
	"testing"
	"time"

	"github.com/manprint/pglens/test/pgtest"
	"github.com/stretchr/testify/require"
)

// INT-WL-002: distinct-queries --count 500 yields 500 distinct queryid values in
// pg_stat_statements on every supported version, 18 included.
func TestINTWL002_DistinctQueries500Queryids(t *testing.T) {
	pgtest.ForEach(t, func(t *testing.T, pg *pgtest.PG) {
		pg.Lock(t)

		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
		defer cancel()

		// Use superuser for extension setup and reset (these require elevated privileges)
		setupPool := pg.Pool(t, "app", pgtest.RoleSuperuser)
		_, err := setupPool.Exec(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
		require.NoError(t, err, "must be able to create pg_stat_statements extension")

		// Clear any existing queries from stat_statements (requires superuser)
		_, err = setupPool.Exec(ctx, "SELECT pg_stat_statements_reset()")
		require.NoError(t, err)

		// Now use RoleT0 for the actual workload queries
		pool := pg.Pool(t, "app", pgtest.RoleT0)

		// Verify that compute_query_id is on (needed for stable queryid)
		var setting string
		err = pool.QueryRow(ctx, "SELECT current_setting('compute_query_id')").Scan(&setting)
		require.NoError(t, err)
		require.Equal(t, "on", setting, "compute_query_id must be on")

		// Run the distinct queries workload with count=500, duration=0 (one-shot, no rotation)
		report := &Report{Details: make(map[string]any)}
		err = distinctQueries(ctx, pool, 500, 0, report)
		require.NoError(t, err, "distinctQueries should succeed")
		require.Equal(t, 500, report.Succeeded, "all 500 generated queries should execute successfully")

		// Query pg_stat_statements for distinct queryid values generated by our workload.
		// The distinctQueries function generates expressions like "SELECT 1+1", "SELECT 1+1+1", etc.
		// for indices < 1000, and wider comma-joined expressions above that.
		// We can identify them by the presence of "+" or "," in the query text.
		var count int
		err = pool.QueryRow(ctx, `
			SELECT count(DISTINCT queryid)
			FROM pg_stat_statements
			WHERE query LIKE '%+%' OR query LIKE '%,%'
		`).Scan(&count)
		require.NoError(t, err, "must be able to query pg_stat_statements")

		// Exactly 500, matching the plan's own literal wording -- verified
		// live (PG15 and PG18) to be reliably exactly 500, not just "close
		// to" 500. count=500 keeps every index below generateExpression's
		// chainThreshold (1000), so every query uses the simple,
		// well-tested single-chain shape with no plausible source of
		// collision or failure at this scale -- a loose tolerance here
		// would only mask a real regression.
		require.Equal(t, 500, count,
			"expected exactly 500 distinct queryid values from 500 generated queries; got %d", count)
	})
}
