FROM golang:1.26 AS builder
ARG VERSION=dev
WORKDIR /src
COPY . .
RUN make build VERSION="$VERSION"
FROM gcr.io/distroless/static-debian12:nonroot
ARG VERSION=dev
LABEL org.opencontainers.image.title="pglens-server" \
      org.opencontainers.image.version="$VERSION" \
      org.opencontainers.image.source="https://github.com/manprint/gitlens"
COPY --from=builder /src/bin/pglens-server /usr/local/bin/pglens-server
HEALTHCHECK CMD ["/usr/local/bin/pglens-server", "--healthcheck"]
USER nonroot
ENTRYPOINT ["/usr/local/bin/pglens-server"]
