FROM golang:1.26 AS builder
WORKDIR /src
COPY . .
RUN make build
FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /src/bin/pglens-server /usr/local/bin/pglens-server
HEALTHCHECK CMD ["/usr/local/bin/pglens-server", "--healthcheck"]
USER nonroot
ENTRYPOINT ["/usr/local/bin/pglens-server"]
