/**
 * This file is generated from ../api/openapi.yaml by openapi-typescript.
 * Regenerate with `make web-gen-api`.
 * Do not edit this file directly.
 */

export interface paths {
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitored clusters. */
        get: operations["getClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the replication topology and failover events for a cluster. */
        get: operations["getClusterTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/replication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return replication lag series for a cluster. */
        get: operations["getClusterReplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/settings-drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return settings that differ between instances in a cluster. */
        get: operations["getClusterSettingsDrift"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitored instances. */
        get: operations["getInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return one instance and its databases. */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return recent activity metrics grouped by metric name. */
        get: operations["getInstanceActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List databases and monitoring status for an instance. */
        get: operations["getInstanceDatabases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return measurable host metrics for an instance. */
        get: operations["getInstanceHost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return observed PostgreSQL settings. */
        get: operations["getInstanceSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return table relation statistics. */
        get: operations["getInstanceTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return index relation statistics. */
        get: operations["getInstanceIndexes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/bloat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return relation bloat estimates. */
        get: operations["getInstanceBloat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/command-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the immutable command audit stream for an instance. */
        get: operations["getInstanceCommandAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the latest sampled blocking tree. */
        get: operations["getLocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query a metric as a time series. */
        get: operations["queryMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events newest first. */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return top statements joined to query text. */
        get: operations["getStatements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return activity samples grouped by the requested dimensions. */
        get: operations["getAsh"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ash/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return top ASH queries joined to their text. */
        get: operations["getAshTop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return plan history for a query. */
        get: operations["getPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts and their suppression state. */
        get: operations["getAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return one alert by alert key. */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alert rules. */
        get: operations["getAlertRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/silences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active silences, or all silences when requested. */
        get: operations["getSilences"];
        put?: never;
        /** Create an alert silence. */
        post: operations["createSilence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List advisor findings. */
        get: operations["getFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return one advisor finding. */
        get: operations["getFinding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the advisor rule catalogue. */
        get: operations["getAdvisorRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a command for an instance. */
        post: operations["createCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the state and result of a command. */
        get: operations["getCommand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a stored alert rule. */
        put: operations["updateAlertRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/silences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** End a silence immediately. */
        delete: operations["deleteSilence"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding-id}/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mute a finding until a future timestamp. */
        post: operations["muteFinding"];
        /** Remove a finding mute. */
        delete: operations["unmuteFinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report the current browser UI session. */
        get: operations["getSession"];
        put?: never;
        /** Create a browser UI session. */
        post: operations["createSession"];
        /** Delete the current browser UI session. */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push an agent envelope to the server. */
        post: operations["pushEnvelope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll and claim the next command for an agent. */
        get: operations["pollCommands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the result of a claimed command. */
        post: operations["submitCommandResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report process liveness. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report database and migration readiness. */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expose Prometheus self-monitoring metrics. */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            detail: string;
        };
        SessionLoginRequest: {
            /** Format: password */
            password: string;
        };
        SessionStatus: {
            authenticated: boolean;
            configured?: boolean;
            /** Format: date-time */
            expires_at?: string;
        };
        /** @description A uint64 rendered as a decimal string because it exceeds the exact integer range of IEEE-754 numbers. */
        ClusterId: string;
        /** Format: uuid */
        InstanceId: string;
        /**
         * Format: date-time
         * @description RFC 3339 timestamp.
         */
        Timestamp: string;
        /** @description Duration in seconds; null means not measured, never zero. */
        NullableSeconds: number | null;
        SeriesPoint: {
            ts: components["schemas"]["Timestamp"];
            value: number | null;
        };
        /** @enum {string} */
        PermTier: "T0" | "T1" | "T2";
        /** @enum {string} */
        Health: "ok" | "degraded" | "critical";
        /** @description True means the relation or cardinality budget cut the result. */
        Truncated: boolean;
        TopologyEdge: {
            from: components["schemas"]["InstanceId"];
            to: components["schemas"]["InstanceId"];
            type: string;
            /** @description sync or async; null when not yet known. */
            sync_state?: string | null;
            /** @enum {string} */
            confidence: "high" | "low";
            note?: string | null;
        };
        Event: {
            /** Format: int64 */
            event_id: number;
            ts: components["schemas"]["Timestamp"];
            type: string;
            cluster_id: string | null;
            /** Format: uuid */
            instance_id: string | null;
            payload: {
                [key: string]: unknown;
            };
        };
        InstanceSummary: {
            instance_id: components["schemas"]["InstanceId"];
            addr: string;
            /** Format: int32 */
            port: number;
            role: string;
            /** Format: int32 */
            pg_version: number;
            perm_tier: components["schemas"]["PermTier"];
            last_seen: components["schemas"]["Timestamp"];
            up: boolean;
        };
        Cluster: {
            cluster_id: components["schemas"]["ClusterId"];
            name: string | null;
            id_source: string;
            /** Format: uuid */
            primary: string | null;
            /** Format: int32 */
            instance_count: number;
            health: components["schemas"]["Health"];
            instances: components["schemas"]["InstanceSummary"][];
            /** Format: int32 */
            standby_count?: number;
            /** Format: int32 */
            sync_standby_count?: number;
            /** @description Largest measurable replay lag; null means not measured, never zero. */
            max_replay_lag_seconds?: components["schemas"]["NullableSeconds"];
            topology?: components["schemas"]["TopologyEdge"][];
        };
        Database: {
            datname: string;
            monitored: boolean;
            skip_reason?: string | null;
        };
        Instance: components["schemas"]["InstanceSummary"] & {
            cluster_id: components["schemas"]["ClusterId"];
            databases: components["schemas"]["Database"][];
            /** Format: int32 */
            databases_not_monitored: number;
        };
        MetricPoint: components["schemas"]["SeriesPoint"];
        MetricsResponse: {
            series: components["schemas"]["MetricPoint"][];
        };
        ReplicationEdge: {
            from: components["schemas"]["InstanceId"];
            to: components["schemas"]["InstanceId"];
            /** @enum {string} */
            metric: "write_lag_sec" | "flush_lag_sec" | "replay_lag_sec";
            sync_state?: string | null;
            series: components["schemas"]["MetricPoint"][];
        };
        ReplicationResponse: {
            cluster_id: components["schemas"]["ClusterId"];
            edges: components["schemas"]["ReplicationEdge"][];
        };
        TopologyResponse: {
            cluster_id: components["schemas"]["ClusterId"];
            topology: components["schemas"]["TopologyEdge"][];
            events: components["schemas"]["Event"][];
        };
        Statement: {
            /** Format: int64 */
            queryid: number;
            datname: string;
            query_text: string;
            calls?: number | null;
            total_exec_time_ms?: number | null;
            rows?: number | null;
            truncated: components["schemas"]["Truncated"];
        };
        StatementsResponse: {
            statements: components["schemas"]["Statement"][];
            truncated: components["schemas"]["Truncated"];
            /** @enum {string} */
            comparable_scope: "cluster";
        };
        AshBucket: {
            ts: components["schemas"]["Timestamp"];
            /** Format: int32 */
            samples: number;
            /** Format: int32 */
            ticks: number;
            /** @description samples divided by ticks; null when ticks is zero, never zero as a sentinel. */
            avg_active_sessions: number | null;
            datname?: string;
            wait_event_type?: string;
            wait_event?: string;
            state?: string;
            /** Format: int64 */
            queryid?: number | null;
        };
        AshResponse: {
            buckets: components["schemas"]["AshBucket"][];
            /** Format: int32 */
            resolution_seconds: number;
            statistical: boolean;
            warning?: string;
            /** @description Present as false when ASH is disabled. */
            enabled?: boolean;
        };
        AshTopEntry: {
            /** Format: int64 */
            queryid: number;
            query_text: string;
            /** Format: int32 */
            samples: number;
            /** Format: int32 */
            ticks: number;
            avg_active_sessions: number | null;
        };
        AshTopResponse: {
            entries: components["schemas"]["AshTopEntry"][];
            /** Format: int32 */
            resolution_seconds: number;
            statistical: boolean;
            warning?: string;
            enabled?: boolean;
        };
        Plan: {
            /** Format: int64 */
            plan_id: number;
            plan_hash: string;
            captured_at: components["schemas"]["Timestamp"];
            analyzed: boolean;
            plan: {
                [key: string]: unknown;
            };
            changed: boolean;
        };
        PlansResponse: {
            plans: components["schemas"]["Plan"][];
            /** Format: int32 */
            total_shapes: number;
        };
        ApiMetric: {
            ts: components["schemas"]["Timestamp"];
            value: number;
            labels: {
                [key: string]: string;
            };
        };
        LocksResponse: {
            instance_id: components["schemas"]["InstanceId"];
            /**
             * Format: date-time
             * @description Null when no lock tree has ever been sampled, not an empty timestamp.
             */
            sampled_at: string | null;
            stale: boolean;
            nodes: {
                [key: string]: unknown;
            }[];
        };
        ActivityResponse: {
            instance_id: components["schemas"]["InstanceId"];
            stale: boolean;
            metrics: {
                [key: string]: components["schemas"]["ApiMetric"][];
            };
        };
        DatabasesResponse: {
            instance_id: components["schemas"]["InstanceId"];
            databases: components["schemas"]["Database"][];
            /** Format: int32 */
            not_monitored_count: number;
        };
        HostResponse: {
            instance_id: components["schemas"]["InstanceId"];
            available: boolean;
            reason?: string;
            source?: string;
            sampled_at?: components["schemas"]["Timestamp"];
            stale?: boolean;
            metrics?: {
                [key: string]: number;
            };
        };
        Setting: {
            name: string;
            value: string | null;
            unit: string;
            source: string;
            context: string;
            pending_restart: string;
            first_seen: components["schemas"]["Timestamp"];
            last_seen: components["schemas"]["Timestamp"];
            changed_at: components["schemas"]["Timestamp"];
        };
        SettingsResponse: {
            instance_id: components["schemas"]["InstanceId"];
            settings: components["schemas"]["Setting"][];
        };
        DriftValue: {
            instance_id: components["schemas"]["InstanceId"];
            role: string;
            value: string;
        };
        DriftEntry: {
            name: string;
            values: components["schemas"]["DriftValue"][];
        };
        RelationResponse: {
            instance_id: components["schemas"]["InstanceId"];
            items: {
                [key: string]: unknown;
            }[];
            truncated: components["schemas"]["Truncated"];
            /** Format: int32 */
            relations_not_reported: number | null;
        };
        Alert: {
            alert_key: string;
            rule_id: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            /** @enum {string} */
            state: "pending" | "firing" | "resolved";
            cluster_id?: components["schemas"]["ClusterId"];
            instance_id?: components["schemas"]["InstanceId"];
            datname: string;
            labels: {
                [key: string]: unknown;
            };
            value: number;
            summary: string;
            started_at: components["schemas"]["Timestamp"];
            last_eval_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            resolved_at: string | null;
            suppressed: boolean;
        };
        AlertRule: {
            id: string;
            severity: string;
            scope: string;
            needs: string[];
            min_tier: components["schemas"]["PermTier"];
        };
        Silence: {
            /** Format: uuid */
            silence_id: string;
            matchers: {
                [key: string]: unknown;
            }[];
            reason: string;
            starts_at: components["schemas"]["Timestamp"];
            ends_at: components["schemas"]["Timestamp"];
        };
        Finding: {
            finding_id: string;
            rule_id: string;
            severity: string;
            /** @enum {string} */
            state: "open" | "degraded" | "muted" | "resolved";
            scope: string;
            cluster_id?: components["schemas"]["ClusterId"];
            instance_id?: components["schemas"]["InstanceId"];
            datname?: string;
            object_name?: string;
            title: string;
            detail?: string;
            remediation?: string;
            evidence?: {
                [key: string]: unknown;
            };
            degraded_reason?: string;
        };
        AdvisorRule: {
            id: string;
            severity: string;
            scope: string;
            needs: string[];
            min_tier: components["schemas"]["PermTier"];
        };
        /** @description Per-kind arguments: explain requires queryid and may include datname or analyze; cancel and terminate require pid; pgstattuple requires schema and relation. Query text is never sent to this API. */
        CommandArgs: {
            queryid?: number | string;
            datname?: string;
            analyze?: boolean;
            /** Format: int32 */
            pid?: number;
            schema?: string;
            relation?: string;
        };
        /** @description A command request contains identifiers and options only; query text is never sent. */
        CreateCommandRequest: {
            /** @enum {string} */
            kind: "explain" | "cancel" | "terminate" | "pgstattuple";
            args: components["schemas"]["CommandArgs"];
        };
        CreateCommandResponse: {
            /** Format: uuid */
            command_id: string;
        };
        CommandResponse: {
            /** Format: uuid */
            command_id: string;
            /**
             * @description Command lifecycle state persisted by the server.
             * @enum {string}
             */
            state: "pending" | "claimed" | "done" | "failed" | "expired";
            result?: unknown;
            error?: string;
        };
        PollCommand: {
            /** Format: uuid */
            command_id: string;
            /** @enum {string} */
            kind: "explain" | "cancel" | "terminate" | "pgstattuple";
            args: components["schemas"]["CommandArgs"];
            instance_id: components["schemas"]["InstanceId"];
            cluster_id: components["schemas"]["ClusterId"];
            /** Format: uuid */
            claim_token: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        /** @description An ok outcome carries result; error and rejected outcomes carry error. The claim token must match the token returned by the poll operation. */
        CommandResultRequest: {
            /** Format: uuid */
            claim_token: string;
            /** @enum {string} */
            outcome: "ok" | "error" | "rejected";
            result?: unknown;
            error?: string;
        };
        AlertRuleUpdate: {
            enabled?: boolean;
            /** @enum {string} */
            severity?: "critical" | "warning" | "info";
            threshold?: number;
            /** Format: int32 */
            for_seconds?: number;
        };
        AlertRuleUpdateResponse: {
            rule_id: string;
            enabled: boolean;
            /** @enum {string} */
            severity: "critical" | "warning" | "info";
            threshold: number;
            /** Format: int32 */
            for_seconds: number;
        };
        SilenceMatcher: {
            name: string;
            value: string;
            is_regex?: boolean;
            negate?: boolean;
        };
        CreateSilenceRequest: {
            /** Format: uuid */
            silence_id?: string;
            matchers: components["schemas"]["SilenceMatcher"][];
            reason: string;
            starts_at: components["schemas"]["Timestamp"];
            ends_at: components["schemas"]["Timestamp"];
        };
        MuteFindingRequest: {
            reason: string;
            until: components["schemas"]["Timestamp"];
        };
        MuteFindingResponse: {
            finding_id: string;
            /** @enum {string} */
            state: "muted";
            muted_until: components["schemas"]["Timestamp"];
            mute_reason: string;
        };
        PushEnvelope: {
            /** Format: int32 */
            protocol_version: number;
            agent_id: string;
            agent_version: string;
            sent_at: components["schemas"]["Timestamp"];
            instances: {
                [key: string]: unknown;
            }[];
        };
        PushResponse: {
            /** Format: int32 */
            accepted: number;
            /** Format: int32 */
            rejected: number;
        };
    };
    responses: {
        /** @description Bad request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request could not be processed. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request payload is too large. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cluster"][];
                };
            };
        };
    };
    getClusterTopology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topology graph and failover events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getClusterReplication: {
        parameters: {
            query: {
                from: components["schemas"]["Timestamp"];
                to: components["schemas"]["Timestamp"];
            };
            header?: never;
            path: {
                id: components["schemas"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lag series by replication edge and metric. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplicationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getClusterSettingsDrift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Differing settings only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftEntry"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSummary"][];
                };
            };
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getInstanceActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent activity; stale true means no fresh sample was observed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceDatabases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database inventory. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabasesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host metrics or an explicit unavailable response; unavailable values are never zero-filled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceSettings: {
        parameters: {
            query?: {
                /** @description Return settings changed at or after this RFC3339 timestamp. */
                changed_since?: components["schemas"]["Timestamp"];
            };
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings observed for the instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceTables: {
        parameters: {
            query?: {
                /** @description Maximum number of relations returned by the instance-level budget. */
                limit?: number;
            };
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table rows and cardinality-budget metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceIndexes: {
        parameters: {
            query?: {
                /** @description Maximum number of relations returned by the instance-level budget. */
                limit?: number;
            };
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index rows and cardinality-budget metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceBloat: {
        parameters: {
            query?: {
                /** @description Maximum number of relations returned by the instance-level budget. */
                limit?: number;
            };
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bloat rows and cardinality-budget metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getInstanceCommandAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getLocks: {
        parameters: {
            query: {
                instance_id: components["schemas"]["InstanceId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lock tree; sampled_at null means no tree was ever sampled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocksResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    queryMetrics: {
        parameters: {
            query: {
                metric: string;
                instance_id: components["schemas"]["InstanceId"];
                database?: string;
                from: components["schemas"]["Timestamp"];
                to: components["schemas"]["Timestamp"];
                /** @description Go duration string; a step producing more than 10000 points returns 422. */
                step: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fixed-step series; missing intervals are null, never zero or interpolated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                cluster_id?: components["schemas"]["ClusterId"];
                type?: string;
                from?: components["schemas"]["Timestamp"];
                to?: components["schemas"]["Timestamp"];
                /** @description Maximum number of events; capped at 1000. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getStatements: {
        parameters: {
            query: {
                instance_id: components["schemas"]["InstanceId"];
                database?: string;
                from?: components["schemas"]["Timestamp"];
                to?: components["schemas"]["Timestamp"];
                order_by?: "calls" | "calls_rate" | "total_calls" | "total_exec_time" | "total_exec_time_ms" | "exec_time" | "total_time" | "total_rows" | "rows" | "rows_rate" | "shared_blks_hit" | "shared_blks_hit_rate" | "shared_blks_read" | "shared_blks_read_rate" | "wal_bytes" | "wal_bytes_rate" | "mean_exec_time" | "mean_time";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top statements and comparability scope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAsh: {
        parameters: {
            query: {
                instance_id: components["schemas"]["InstanceId"];
                from?: components["schemas"]["Timestamp"];
                to?: components["schemas"]["Timestamp"];
                group_by?: "wait_event_type" | "wait_event" | "queryid" | "state" | "datname";
                database?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ASH buckets; avg_active_sessions is null when ticks is zero. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AshResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAshTop: {
        parameters: {
            query: {
                instance_id: components["schemas"]["InstanceId"];
                from?: components["schemas"]["Timestamp"];
                to?: components["schemas"]["Timestamp"];
                database?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top ASH queries; disabled ASH is represented explicitly with enabled false. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AshTopResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPlans: {
        parameters: {
            query: {
                queryid: number | string;
                instance_id?: components["schemas"]["InstanceId"];
                datname?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan history newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlansResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAlerts: {
        parameters: {
            query?: {
                state?: "pending" | "firing" | "resolved" | "all";
                severity?: string;
                rule_id?: string;
                instance_id?: components["schemas"]["InstanceId"];
                cluster_id?: components["schemas"]["ClusterId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alerts, capped by the server at 500 entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Built-in and stored alert rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"][];
                };
            };
        };
    };
    getSilences: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silences ordered by end time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Silence"][];
                };
            };
        };
    };
    createSilence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSilenceRequest"];
            };
        };
        responses: {
            /** @description Silence created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Silence"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Alert storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFindings: {
        parameters: {
            query?: {
                state?: string;
                severity?: string;
                rule_id?: string;
                datname?: string;
                scope?: string;
                instance_id?: components["schemas"]["InstanceId"];
                cluster_id?: components["schemas"]["ClusterId"];
                /** @description Maximum findings; default 100 and maximum 1000. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Findings ordered by severity and recency. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "finding-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finding detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAdvisorRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Advisor rule catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorRule"][];
                };
            };
        };
    };
    createCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommandRequest"];
            };
        };
        responses: {
            /** @description Command accepted and queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Command storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command state and optional result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Command storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleUpdate"];
            };
        };
        responses: {
            /** @description Updated alert rule settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleUpdateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Built-in tier-0 rules cannot be changed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Alert storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSilence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silence ended; no response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Alert storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    muteFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "finding-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteFindingRequest"];
            };
        };
        responses: {
            /** @description Finding muted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuteFindingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Findings storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unmuteFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "finding-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finding unmuted; no response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Findings storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A valid browser session is active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "authenticated": true,
                     *       "expires_at": "2026-08-31T13:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
            /** @description No valid browser session is active. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionLoginRequest"];
            };
        };
        responses: {
            /** @description Session created; the response sets the pglens_session cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted; the response expires the pglens_session cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    pushEnvelope: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushEnvelope"];
            };
        };
        responses: {
            /** @description Envelope accepted for processing. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
            /** @description Ingest failed while checking or storing the envelope. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    pollCommands: {
        parameters: {
            query?: {
                /** @description Go duration to wait; negative values are rejected and values above 30s are capped. */
                wait?: string;
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A command was claimed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollCommand"];
                };
            };
            /** @description No command became available before the wait elapsed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The authenticated agent does not own the requested queue. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Command polling failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitCommandResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandResultRequest"];
            };
        };
        responses: {
            /** @description Command result accepted; no response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Claim token did not match, or the command was expired or no longer claimed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Command result could not be persisted. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Command storage is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example ok */
                    "text/plain": string;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example ok */
                    "text/plain": string;
                };
            };
            /** @description The server is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example not ready */
                    "text/plain": string;
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus exposition text; the payload is intentionally not modeled as JSON. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example # HELP pglens_up 1 if the instance agent is reachable */
                    "text/plain": unknown;
                };
            };
        };
    };
}
