import { astToString, default as openapiTS } from 'openapi-typescript'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, resolve } from 'node:path'
import { writeFile } from 'node:fs/promises'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(scriptDirectory, '../..')
const sourcePath = resolve(repositoryRoot, 'api/openapi.yaml')
const outputPath = resolve(repositoryRoot, 'web/src/api/generated.ts')

const ast = await openapiTS(pathToFileURL(sourcePath))
const generated = astToString(ast)
const header = `/**
 * This file is generated from ../api/openapi.yaml by openapi-typescript.
 * Regenerate with \`make web-gen-api\`.
 * Do not edit this file directly.
 */

`

await writeFile(outputPath, `${header}${generated}`, 'utf8')
